CXX = g++

NAME = eagler

LIB_DIR = ../lib
SRC_DIR = ../src
OBJ_DIR = obj

CXX_FLAGS += -std=c++11
CXX_FLAGS += -I../vendor/seqan/include
CXX_FLAGS += -I$(LIB_DIR) -I$(LIB_DIR)/poa/include
CXX_FLAGS += -W -Wall -Wno-long-long -pedantic -Wno-variadic-macros
LD_FLAGS = -L$(LIB_DIR)

POA_DIR = $(LIB_DIR)/poa
LIB_POA = $(POA_DIR)/lib/libcpppoa.a

CPP_FILES = $(shell find $(SRC_DIR) -type f -iname \*.cpp)
OBJ_FILES = $(subst $(SRC_DIR), $(OBJ_DIR), $(addsuffix .o, $(basename $(CPP_FILES))))
DEP_FILES = $(OBJ_FILES:.o=.d)

UNAME_S := $(shell uname -s)

ifeq ($(UNAME_S),Linux)
	# add rt library linking on Linux OS
	LD_FLAGS+=-lrt
endif
ifeq ($(UNAME_S),Darwin)
	# attempts to select the highest g++ version available

	compiler := $(shell g++-4.8 --version 2>/dev/null)
	ifdef compiler
		CXX = g++-4.8
	endif

	compiler := $(shell g++-4.9 --version 2>/dev/null)
	ifdef compiler
		CXX = g++-4.9
	endif

	compiler := $(shell g++-5 --version 2>/dev/null)
	ifdef compiler
		CXX = g++-5
	endif
endif

default: all

all: $(NAME) $(OBJ_FILES)

$(NAME): $(OBJ_FILES) $(LIB_POA)
	@echo [LD] $@
	@$(CXX) $(LD_FLAGS) -o $@ $^

$(OBJ_DIR)/%.o: $(SRC_DIR)/%.cpp
	@echo [CC] $<
	@mkdir -p $(dir $@)
	@$(CXX) $(CXX_FLAGS) -c -MMD -o $@ $<

$(OBJ_FILES): | poa

poa:
	@$(MAKE) -C ../lib/poa $(MODULE)

clean:
	@echo [RM] cleaning $(MODULE)
	@rm -rf $(OBJ_DIR) $(NAME)

.PHONY: default all poa clean

-include $(DEP_FILES)
